version: '1'

networks:
  marine:
    external: true

services:
  movie-backend:
    container_name: movie-backend
    image: marine-movie-backend:0.1.0
    build: .
    restart: always
    environment:
      PORT: ${PORT}
      DATABASE_URL: ${DATABASE_URL}
      SECRET_SEED: ${SECRET_SEED}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      BUCKET_NAME: ${BUCKET_NAME}
    networks:
      - marine
    
